spring:
  application:
    name: rinhadeconcurseiro

  # Banco de Dados
  datasource:
    url: jdbc:postgresql://localhost:5432/rinhadeconcurseiro
    username: postgres
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  # OAuth2 (configuraremos depois)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email

# Logging
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web.client: DEBUG
    br.com.rinhadeconcurseiro: DEBUG

# Servidor
server:
  port: 8080